FROM spark:3.5.3-python3
USER root
RUN apt update
RUN apt-get install -y git
WORKDIR /
RUN mkdir files
COPY ./files/countries_and_continents.csv /files
COPY ./files/owid_monkeypox_data.csv /files
COPY ./files/worldometer_coronavirus_daily_data.csv /files
RUN git clone https://github.com/Toastaspiring/MSPR-ANALIZE-IT.git
WORKDIR /MSPR-ANALIZE-IT
RUN git checkout ETL
RUN pip install --upgrade pip
#[ "/opt/spark/bin/pyspark" ]