services:
  db:
    container_name: db_mspr
    image: mariadb:11.6.1-noble-rc
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw3rdR00t
    volumes:
      - ./init_db_script:/docker-entrypoint-initdb.d/

  phpmyadmin:
    container_name: phpmyadmin_mspr
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8095:80
    environment:
      - PMA_HOST:db
      - PMA_PORT:3306 
      - PMA_ARBITRARY:1
    depends_on:
      - db

  etl:
    container_name: etl_mspr
    build:
      context: .
      dockerfile: Dockerfile-etl
    command: sleep infinity

  api:
    container_name: api_mspr
    build:
      context: .
      dockerfile: Dockerfile-api
    command: sleep infinity
    ports:
      - 3000:3000
    
    
  front:
    container_name: front_mspr
    build:
      context: .
      dockerfile: Dockerfile-front
    command: sleep infinity
    ports:
      - 5173:5173
    
