services:
  db:
    image: mariadb:11.6.1-noble-rc
    environment:
      MARIADB_ROOT_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin:5.2.1-fpm-alpine
    restart: always
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
  Api:
    image: python:3.14.0a1-alpine3.20
  front: 
    image: node:23-alpine3.19