FROM spark:3.5.3-python3
USER root
RUN apt update
RUN apt-get install -y git
WORKDIR /
RUN git clone https://github.com/Toastaspiring/MSPR-ANALIZE-IT.git
WORKDIR /MSPR-ANALIZE-IT
RUN git checkout ETL
RUN pip install --upgrade pip
ENTRYPOINT [ "/opt/spark/bin/pyspark" ]