services:
  db:
    image: mariadb:11.6.1-noble-rc
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
        - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8095:80
    environment:
      - PMA_HOST:db
      - PMA_PORT:3306 
      - PMA_ARBITRARY:1
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: sleep infinity
    
    
  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    command: sleep infinity
    

volumes:
  db: