services:
  sonarqube_mspr:
    build:
      context: .
      dockerfile: Dockerfile-sonar
    container_name: sonarqube_mspr
    depends_on:
      - db_sonar
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db_sonar:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar    
    

  db_sonar:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    ports:
      - "5432:5432"