# This is a basic workflow to help you get started with Actions

name: auto docker build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: regle de firewall
        run: sudo ufw allow 8095/tcp && sudo ufw allow 3000/tcp && sudo ufw allow 5173/tcp && sudo ufw allow 3000/tcp

      # Runs a single command using the runners shell
      - name: run docker compose 
        run: docker compose up -d
    
      - name: check health
        run: |
            sleep 75
            docker ps
    
      - name: test access
        run: |
            curl http://localhost:8095 || exit 1
            curl http://localhost:3000/api || exit 1
            curl http://localhost:5173 || exit 1

